Telemonitoreo/Telemonitoreo/Models/MensajeEducacionalViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Telemonitoreo.Models
{
    public class MensajeEducacionalViewModel
    {
        public int IdMensajeEducacional { get; set; }
        [Required]
        [Display(Name = "Semana de Embarazo")]
        public string SemanaEmbarazo { get; set; }
        public byte EstadoId { get; set; }
        public int UsuarioEditor { get; set; }
        public virtual ICollection<ContenidoMensajeEducacionalViewModel> Contenido { get; set; } 
    }

    public class ContenidoMensajeEducacionalViewModel
    {
        public int IdContenidoMensajeEducacional { get; set; }
        public int IdMensajeEducacional { get; set; }
        [Display(Name = "Día")]
        public byte DiaSemana { get; set; }
        [Display(Name = "Contenido")]
        public string Contenido { get; set; }
        public virtual MensajeEducacionalViewModel MensajeEducacional { get; set; } 
    }

    public class MensajeEducacionalListViewModel
    {
        [Display(Name = "ID de Registro")]
        public int IdMensajeEducacional { get; set; }
        [Display(Name = "Semana de Embarazo")]
        public string SemanaEmbarazo { get; set; }
        [Display(Name = "Configurado Por")]
        public string UsuarioConfigurador { get; set; }
        [Display(Name = "Establecimiento")]
        public string Establecimiento { get; set; }
        [Display(Name = "Fecha de Creación")]
        public DateTime? FechaCreacion { get; set; }
    }

}

Telemonitoreo/Telemonitoreo/Controllers/MensajeEducacionalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Telemonitoreo.Business;
using Telemonitoreo.Enums;
using Telemonitoreo.Models;

namespace Telemonitoreo.Controllers
{
    public class MensajeEducacionalController : BaseController
    {
        private readonly MensajeEducacionalManager _mensajeEducacionalManager = new MensajeEducacionalManager();
        private readonly EstablecimientoManager _establecimientoManager = new EstablecimientoManager();
        //
        // GET: /MensajeEducacional/
        public ActionResult Index()
        {
            ConfigurarMenues();
            RegistrarAccion((byte)AccionSesion.Accesar, (byte)ObjetoSesion.ListaMensEducacion, null);
            ViewBag.EstablecimientoId = new SelectList(_establecimientoManager.ListarEstablecimientos(), "EstablecimientoId", "Descripcion");
            return View();
        }

        //
        // GET: /MensajeEducacional/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /MensajeEducacional/Create
        public ActionResult Crear()
        {
            ConfigurarMenues();
            RegistrarAccion((byte)AccionSesion.Accesar, (byte)ObjetoSesion.CrearMensEducacion, null);
            return View();
        }

        //
        // POST: /MensajeEducacional/Create
        [HttpPost]
        public JsonResult Crear(MensajeEducacionalViewModel mensajeEducacional)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    mensajeEducacional.UsuarioEditor = ObtenerUsuarioKeyLogeado();
                    var result = _mensajeEducacionalManager.GrabarMensaje(mensajeEducacional);

                    switch (result)
                    {
                        case 0:
                            return
                                Json(
                                    new
                                    {
                                        Success = 0,
                                        ex = new Exception("No se pudo registrar el mensaje.").Message.ToString()
                                    });
                        case -1:
                            return
                                Json(
                                    new
                                    {
                                        Success = 0,
                                        ex = new Exception("Ya fueron configurados mensajes para la semana.").Message.ToString()
                                    });
                    }

                    RegistrarAccion((byte)AccionSesion.Crear, (byte)ObjetoSesion.CrearMensEducacion, result);
                    return Json(new { Success = 1, IdMensajeEducacional = result, ex = "" });
                }
            }
            catch (Exception ex)
            {
                // If Sucess== 0 then Unable to perform Save/Update Operation and send Exception to View as JSON 
                return Json(new { Success = 0, ex = ex.Message.ToString() });
            }

            return Json(new { Success = 0, ex = new Exception("No se pudo registrar  el mensaje").Message.ToString() });
        }

        //
        // GET: /MensajeEducacional/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegistrarAccion((byte)AccionSesion.Accesar, (byte)ObjetoSesion.EditarMensEducacion, null);
            var mensajeEducacional = _mensajeEducacionalManager.MostrarMensajeEducacional((int)id);

            if (mensajeEducacional == null)
            {
                return HttpNotFound();
            }
            ConfigurarMenues();
            return View(mensajeEducacional);
        }

        //
        // POST: /MensajeEducacional/Edit/5
        [HttpPost]
        public JsonResult Edit(MensajeEducacionalViewModel mensajeEducacional)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var result = _mensajeEducacionalManager.GrabarMensaje(mensajeEducacional);

                    if (result < 1)
                        return
                            Json(
                                new
                                {
                                    Success = 0,
                                    ex = new Exception("No se pudo registrar el mensaje.").Message.ToString()
                                });

                    RegistrarAccion((byte)AccionSesion.Actualizar, (byte)ObjetoSesion.EditarMensEducacion, result);
                    return Json(new { Success = 1, IdMensajeEducacional = result, ex = "" });
                }
            }
            catch (Exception ex)
            {
                // If Sucess== 0 then Unable to perform Save/Update Operation and send Exception to View as JSON 
                return Json(new { Success = 0, ex = ex.Message.ToString() });
            }

            return Json(new { Success = 0, ex = new Exception("No se pudo registrar el mensaje.").Message.ToString() });
        } 

        //
        // GET: /MensajeEducacional/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /MensajeEducacional/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult BuscarMensajeEducacional(string establecimiento, string fechaIni, string fechaFin, string semana)
        {
            var page = Convert.ToInt32(Request.Params["page"]);
            var records = Convert.ToInt32(Request.Params["rows"]);
            var sortColumn = Request.Params["sidx"] ?? "";
            var sortDirection = Request.Params["sord"] ?? "asc";

            RegistrarAccion((byte)AccionSesion.Buscar, (byte)ObjetoSesion.ListaMensEducacion, null);
            var listaMensajesEducacionales = _mensajeEducacionalManager.ListarMensajesEducacionales(establecimiento, fechaIni, fechaFin, semana,sortColumn, sortDirection);
            var count = listaMensajesEducacionales.Count;

            var jsonDataObject = new
            {
                page = page,
                total = (int)Math.Ceiling((double)count / records),
                records = count,
                rows = listaMensajesEducacionales.Skip((page - 1) * records).Take(records)
            };
            return new JsonResult()
            {
                Data = jsonDataObject,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                MaxJsonLength = Int32.MaxValue
            };
        }

        // POST: /MensajeEducacional/Eliminar
        [HttpPost]
        public JsonResult Eliminar(List<int> ids)
        {
            try
            {
                _mensajeEducacionalManager.EliminarMensajeEducacional(ids);
                ids.ForEach(i => RegistrarAccion((byte)AccionSesion.Eliminar, (byte)ObjetoSesion.ListaMensEducacion, i));
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
            return Json(true);
        }
    }
}

Telemonitoreo/Telemonitoreo/Views/MensajeEducacional/Crear.cshtml
@model Telemonitoreo.Models.MensajeEducacionalViewModel
@using Telemonitoreo.Utils;

@{
    ViewBag.Title = "Crear";
}

<h2>Ingreso de Mensajes Educacionales</h2>
@Styles.Render("~/Content/DataTables-1.8.1/extras/TableTools/media/css/css")

@{
    var diaListItems = new List<SelectListItem>
    {
        new SelectListItem
        {
            Text =  GlobalConstants.Dia1,
            Value = "1"
        },
        new SelectListItem
        {
            Text =  GlobalConstants.Dia2,
            Value = "2"
        },
        new SelectListItem
        {
            Text =  GlobalConstants.Dia3,
            Value = "3"
        },
        new SelectListItem
        {
            Text =  GlobalConstants.Dia4,
            Value = "4"
        },
        new SelectListItem
        {
            Text =  GlobalConstants.Dia5,
            Value = "5"
        },
        new SelectListItem
        {
            Text =  GlobalConstants.Dia6,
            Value = "6"
        },
        new SelectListItem
        {
            Text =  GlobalConstants.Dia7,
            Value = "7"
        }

    };
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary("", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SemanaEmbarazo, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.SemanaEmbarazo, new { htmlAttributes = new { @class = "form-control", @maxlength = "2"} })
            </div>
        </div>
        <fieldset style="border: 1px solid #C0C0C0; padding: 10px; width: 70%;">
            <legend style="font-weight: bold; margin: 0px; border: 0px; width: auto; font-size: 18px;">Contenido de Mensajes</legend>
            <div class="form-group">
                <label class="col-md-2 control-label">Día</label>
                <div class="col-md-10">
                    @Html.DropDownList("Dia", diaListItems, GlobalConstants.SeleccioneDia, new { @class = "form-control" })
                    
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Contenido</label>
                <div class="col-md-10">
                    <div class="input-group">
                        @Html.TextArea("Contenido", "", htmlAttributes: new { @class = "form-control", @style = "-moz-resize: none;-ms-resize: none;-o-resize: none;resize: none;" })
                        <span class="input-group-btn" style="width: 10% !important;">
                            <button type="button" class="btn btn-primary" onclick=" AddContenido(); ">+</button>
                        </span>
                    </div>
                </div>
            </div>
            <table class="tbl hijos" id="tbl">
                <thead>
                    <tr>
                        <th style="width: 150px;">Día</th>
                        <th style="width: 450px;">Contenido</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model.Contenido)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayTextFor(i => item.DiaSemana)
                                </td>
                                <td>
                                    @Html.DisplayTextFor(i => item.Contenido)
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <input type="button" value="Borrar Contenido" onclick=" DeleteContenido() " />
        </fieldset>
        <br/>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Grabar" class="btn btn-primary" onclick="GuardarContenido()" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Ver Listado de Mensajes Educacionales", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqDatePicker")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/DataTables")
    @Scripts.Render("~/bundles/jqMensajeEducacionalForm")
    <script type="text/javascript">
    var DiaUno = "@Html.Raw(GlobalConstants.Dia1)";
    var DiaDos = "@Html.Raw(GlobalConstants.Dia2)";
    var DiaTres = "@Html.Raw(GlobalConstants.Dia3)";
    var DiaCuatro = "@Html.Raw(GlobalConstants.Dia4)";
    var DiaCinco = "@Html.Raw(GlobalConstants.Dia5)";
    var DiaSeis = "@Html.Raw(GlobalConstants.Dia6)";
    </script>
}

Telemonitoreo/Telemonitoreo/Views/MensajeEducacional/Edit.cshtml
@using Telemonitoreo.Utils;
@model Telemonitoreo.Models.MensajeEducacionalViewModel
@{
    ViewBag.Title = "Edit";
}

<h2>Editar Mensajes Educacionales</h2>
@Styles.Render("~/Content/DataTables-1.8.1/extras/TableTools/media/css/css")

@{
    var diaListItems = new List<SelectListItem>
    {
        new SelectListItem
        {
            Text =  GlobalConstants.Dia1,
            Value = "1"
        },
        new SelectListItem
        {
            Text =  GlobalConstants.Dia2,
            Value = "2"
        },
        new SelectListItem
        {
            Text =  GlobalConstants.Dia3,
            Value = "3"
        },
        new SelectListItem
        {
            Text =  GlobalConstants.Dia4,
            Value = "4"
        },
        new SelectListItem
        {
            Text =  GlobalConstants.Dia5,
            Value = "5"
        },
        new SelectListItem
        {
            Text =  GlobalConstants.Dia6,
            Value = "6"
        },
        new SelectListItem
        {
            Text =  GlobalConstants.Dia7,
            Value = "7"
        }

    };
}

@helper RenderDia(byte diaSemana)
{
    switch (diaSemana)
    {
        case 1:
            @GlobalConstants.Dia1
            break;
        case 2:
            @GlobalConstants.Dia2
            break;
        case 3:
            @GlobalConstants.Dia3
            break;
        case 4:
            @GlobalConstants.Dia4
            break;
        case 5:
            @GlobalConstants.Dia5
            break;
        case 6:
            @GlobalConstants.Dia6
            break;
        default:
            @GlobalConstants.Dia7
            break;
    }
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary("", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdMensajeEducacional, new { htmlAttributes = new { @class = "form-control" } })
        <div class="form-group">
            @Html.LabelFor(model => model.SemanaEmbarazo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SemanaEmbarazo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>
        <fieldset style="border: 1px solid #C0C0C0; padding: 10px; width: 70%;">
            <legend style="font-weight: bold; margin: 0px; border: 0px; width: auto; font-size: 18px;">Contenido de Mensajes</legend>
            <div class="form-group">
                <label class="col-md-2 control-label">Día</label>
                <div class="col-md-10">
                    @Html.DropDownList("Dia", diaListItems, GlobalConstants.SeleccioneDia, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Contenido</label>
                <div class="col-md-10">
                    <div class="input-group">
                        @Html.TextArea("nContenido", "", htmlAttributes: new { @class = "form-control", @style = "-moz-resize: none;-ms-resize: none;-o-resize: none;resize: none;" })
                        <span class="input-group-btn" style="width: 10% !important;">
                            <button type="button" class="btn btn-primary" onclick=" AddContenidoEdit(); ">+</button>
                        </span>
                    </div>
                </div>
            </div>
            <table class="tbl hijos" id="tbl">
                <thead>
                <tr>
                    <th style="width: 40px;">ID</th>
                    <th style="width: 140px;">Día</th>
                    <th style="width: 420px;">Contenido</th>
                </tr>
                </thead>

                <tbody>
                @if (Model != null)
                {
                    foreach (var item in Model.Contenido)
                    {
                        <tr>
                            <td>
                                @Html.DisplayTextFor(i => item.IdContenidoMensajeEducacional)
                            </td>
                            <td>
                                @RenderDia(item.DiaSemana)
                            </td>
                            <td>
                                @Html.DisplayTextFor(i => item.Contenido)
                            </td>
                        </tr>
                    }
                }
                </tbody>
            </table>
            <input type="button" value="Borrar Contenido" onclick=" DeleteContenido() "/>
        </fieldset>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Grabar" class="btn btn-primary" onclick="GuardarContenidoEdit();" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Ver Listado de Mensajes Educacionales", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqDatePicker")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/DataTables")
    @Scripts.Render("~/bundles/jqMensajeEducacionalForm")
    <script type="text/javascript">
    var DiaUno = "@Html.Raw(GlobalConstants.Dia1)";
    var DiaDos = "@Html.Raw(GlobalConstants.Dia2)";
    var DiaTres = "@Html.Raw(GlobalConstants.Dia3)";
    var DiaCuatro = "@Html.Raw(GlobalConstants.Dia4)";
    var DiaCinco = "@Html.Raw(GlobalConstants.Dia5)";
    var DiaSeis = "@Html.Raw(GlobalConstants.Dia6)";
    </script>
}

Telemonitoreo/Telemonitoreo/Views/MensajeEducacional/Index.cshtml
@using Telemonitoreo.Utils;

@{
    ViewBag.Title = "Lista de Mensajes Educacionales";
}

<h2>Lista de Mensajes Educacionales</h2>
@using (Html.BeginForm("ExportExcel", "MensajeEducacional", FormMethod.Post, new
{
    id = "ListadoMensajeEducacional",
    enctype = "multipart/form-data"
}))
{
    <div class="row">
        <div class="col-md-4">
            <div class="col-md-3">
                <label>Est. de Salud</label>
            </div>
            <div class="col-md-9">
                @Html.DropDownList("EstablecimientoId", null, GlobalConstants.SeleccioneEstablecimiento, htmlAttributes: new {@class = "form-control"})
            </div>
        </div>
        <div class="col-md-4">
            <div class="col-md-3">
                <label for="FechaI">Fecha Inicio (Creación)</label>
            </div>
            <div class="col-md-9">
                <input name="FechaI" class="text-box single-line datepicker textbox-bring-to-front" id="FechaI" type="text">
            </div>
        </div>

        <div class="col-md-4">
            <div class="col-md-3">
                <label for="FechaF">Fecha Fin (Creación)</label>
            </div>
            <div class="col-md-9">
                <input name="FechaF" class="text-box single-line datepicker textbox-bring-to-front" id="FechaF" type="text">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="col-md-3">
                <label for="Semana">Semana de Embarazo</label>
            </div>
            <div class="col-md-9">
                <input name="Semana" class="form-control" id="Semana" type="text">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-8">
            <div class="col-md-9 col-md-offset-3">
                <input name="btnBuscar" class="btn btn-primary btn-group-sm" id="btnBuscar" type="button" value="Buscar">
            </div>
        </div>
    </div>
}
<div class="row">
    <div class="col-md-11">
        <table id="gridView"><tr><td></td></tr></table>
        <div id="pager"></div>
    </div>
</div>
<div class="row">
    <div class="col-md-8 text-left">
        <input name="btnEliminar" class="btn btn-primary" id="btnEliminar" type="button" value="Deshabilitar">
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqMensajeEducacional")
    @Scripts.Render("~/bundles/jqDatePicker")
}