Telemonitoreo/Telemonitoreo/Models/EstablecimientoViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Telemonitoreo.Models
{
    public class ListaEstabViewModel
    {
        public int EstablecimientoId { get; set; }
        public int? Renaes { get; set; }
        public string Descripcion { get; set; }
        public string Direccion { get; set; }
        public string Estado { get; set; }
        public string Distrito { get; set; }
        public string Provincia { get; set; }
        public string Region { get; set; }
    }
}

Telemonitoreo/Telemonitoreo/Controllers/EstablecimientoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web.Mvc;
using Telemonitoreo.Business;
using Telemonitoreo.Enums;
using Telemonitoreo.Utils;

namespace Telemonitoreo.Controllers
{
    public class EstablecimientoController : BaseController
    {
        readonly EstablecimientoManager _establecimientoManager = new EstablecimientoManager();
        readonly UtilManager _utilManager = new UtilManager();
        //
        // GET: /Establecimiento/
        public ActionResult Index()
        {
            ConfigurarMenues();
            RegistrarAccion((byte)AccionSesion.Accesar, (byte)ObjetoSesion.ListaEstablecimientos, null);
            ViewBag.Estado = new SelectList(_utilManager.ListarEstados(), "Id", "Descripcion");
            return View();
        }

        public int GetEstablecimientosRenaes()
        {
            RegistrarAccion((byte)AccionSesion.Actualizar, (byte)ObjetoSesion.RenaesEstablecimientos, null);

            new Thread(() =>
            {
                //Do an advanced looging here which takes a while
                var updateEstablecimientos = _establecimientoManager.ActualizarBaseEstablecimientos("");
            }).Start();

            
            return 1;
        }

        // GET: BuscarGestantes
        public ActionResult BuscarEstablecimientos(string codRenaes, string nomEst, string estado)
        {
            var page = Convert.ToInt32(Request.Params["page"]);
            var records = Convert.ToInt32(Request.Params["rows"]);
            var sortColumn = Request.Params["sidx"] ?? "";
            var sortDirection = Request.Params["sord"] ?? "asc";

            RegistrarAccion((byte)AccionSesion.Buscar, (byte)ObjetoSesion.ListaEstablecimientos, null);

            var listaEstablecimientos = _establecimientoManager.BuscarEstablecimientos(codRenaes, nomEst, estado, sortColumn, sortDirection);
            var count = listaEstablecimientos.Count;

            var jsonDataObject = new
            {
                page = page,
                total = (int)Math.Ceiling((double)count / records),
                records = count,
                rows = listaEstablecimientos.Skip((page - 1) * records).Take(records)
            };
            return new JsonResult()
            {
                Data = jsonDataObject,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                MaxJsonLength = Int32.MaxValue
            };
        }

        [HttpPost]
        public JsonResult Deshabilitar(List<int> ids)
        {
            try
            {
                var listaEst =_establecimientoManager.DeshabilitarEstablecimientos(ids);
                listaEst.ForEach(i => RegistrarAccion((byte)AccionSesion.Actualizar, (byte)ObjetoSesion.ListaEstablecimientos, i));
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
            return Json(true);
        }

        [HttpPost]
        public JsonResult Habilitar(List<int> ids)
        {
            try
            {
                var listaEst = _establecimientoManager.HabilitarEstablecimientos(ids);

                foreach (var item in listaEst)
                {
                    RegistrarAccion((byte)AccionSesion.Actualizar, (byte)ObjetoSesion.ListaEstablecimientos, item);
                }
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
            return Json(true);
        }

        public ActionResult ExportarExcel(FormCollection form)
        {
            try
            {
                var codRenaes = form["Codigo"];
                var nomEst = form["Nombre"];
                var estado = string.IsNullOrWhiteSpace(form["Estado"]) ? "" : form["Estado"];
                var sortColumn = form["hdSortColumn"] ?? "UsuarioKey";
                var sortDirection = form["hdSortDirection"] ?? "asc";

                RegistrarAccion((byte)AccionSesion.ExportExcel, (byte)ObjetoSesion.ListaEstablecimientos, null);
                var listaEstablecimientos = _establecimientoManager.BuscarEstablecimientos(codRenaes, nomEst, estado, sortColumn, sortDirection);

                var listaEstablecimientosExcel = from o in listaEstablecimientos
                                                 select new
                                                 {
                                                     COD_RENAES = o.Renaes != null ? o.Renaes.ToString() : "",
                                                     Nombre = o.Descripcion,
                                                     o.Direccion,
                                                     Distrito = o.Distrito,
                                                     Provincia = o.Provincia,
                                                     Region = o.Region,
                                                     o.Estado
                                                 };

                ExcelExport.ExportToSpreadsheet(listaEstablecimientosExcel.CopyToDataTable(), "Establecimientos");
                return View();
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e;
                return PartialView("Error");
            }
        }
	}
}

Telemonitoreo/Telemonitoreo/Views/Establecimiento/Index.cshtml
@using Telemonitoreo.Utils

@{
    ViewBag.Title = "Lista de Establecimientos";
}

<h2>Lista de Establecimientos</h2>
@using (Html.BeginForm("ExportarExcel", "Establecimiento", FormMethod.Post, new { id = "ListadoEstablecimientos", enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-md-4">
            <div class="col-md-3">
                <label for="Codigo">Código RENAES</label>
            </div>
            <div class="col-md-9">
                <input name="Codigo" class="form-control" id="Codigo" type="text">
            </div>
        </div>
        <div class="col-md-4">
            <div class="col-md-3">
                <label for="Nombre">Nombre</label>
            </div>
            <div class="col-md-9">
                <input name="Nombre" class="form-control" id="Nombre" type="text">
            </div>
        </div>
        <div class="col-md-4">
            <div class="col-md-3">
                <label for="Estado">Estado</label>
            </div>
            <div class="col-md-9">
                @Html.DropDownList("Estado", null, GlobalConstants.SeleccioneEstado, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-8">
            <div class="col-md-9 col-md-offset-3">
                <input name="btnBuscar" class="btn btn-primary btn-group-sm" id="btnBuscar" type="button" value="Buscar">
            </div>
        </div>
    </div>
    <input type="hidden" id="hdSortColumn" name="hdSortColumn" >
    <input type="hidden" id="hdSortDirection" name="hdSortDirection" >
}
<div class="row">
    <div class="col-md-11">
        <div class="text-left">
            <input name="btnActualizar" class="btn btn-primary" id="btnActualizar" type="button" value="Actualizar Establecimientos" >
            @*<input name="btnExportarExcel" class="btn btn-primary btn-group-sm" id="btnExportarExcel" type="button" value="Exportar">*@
        </div>
        <table id="gridView"><tr><td></td></tr></table>
        <div id="pager"></div>
    </div>
</div>
<div class="row">
    <div class="col-md-8 text-left">
        @*<input name="btnDeshabilitar" class="btn btn-primary" id="btnDeshabilitar" type="button" value="Deshabilitar">*@
        @*<input name="btnHabilitar" class="btn btn-primary" id="btnHabilitar" type="button" value="Habilitar" style="margin-left: 15px;">*@
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqEstablecimientos")
}