Telemonitoreo/Telemonitoreo/Controllers/GestanteMedicamentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Telemonitoreo.Business;
using Telemonitoreo.Enums;
using Telemonitoreo.Models;

namespace Telemonitoreo.Controllers
{
    public class GestanteMedicamentoController : BaseController
    {
        private readonly EstablecimientoManager _establecimientoManager = new EstablecimientoManager();
        private readonly UtilManager _utilManager = new UtilManager();
        private readonly GestanteManager _gestanteManager = new GestanteManager();
        //
        // GET: /GestanteMedicamento/
        public ActionResult Index()
        {
            ConfigurarMenues();
            RegistrarAccion((byte)AccionSesion.Accesar, (byte)ObjetoSesion.ListaGestanteMedicamento, null);
            ViewBag.EstablecimientoId = new SelectList(_establecimientoManager.ListarEstablecimientos(), "EstablecimientoId", "Descripcion");
            return View();
        }
        public ActionResult Crear()
        {
            ConfigurarMenues();
            RegistrarAccion((byte)AccionSesion.Accesar, (byte)ObjetoSesion.CrearGestanteMedicamento, null);
            ViewBag.EstablecimientoId = new SelectList(_establecimientoManager.ListarEstablecimientos(), "EstablecimientoId", "Descripcion");
            //ViewBag.MedicamentoId = new SelectList(_utilManager.ListarMedicamentos(), "EstablecimientoId", "Descripcion");
            return View();
        }

        // POST: /Sales/Create 
        /// <summary> 
        /// This method is used for Creating and Updating  Sales Information  
        /// (Sales Contains: 1.SalesMain and *SalesSub ) 
        /// </summary> 
        /// <param name="gestanteMedicamentos"> 
        /// </param> 
        /// <returns> 
        /// Returns Json data Containing Success Status, New Sales ID and Exeception  
        /// </returns> 
        [HttpPost]
        public JsonResult Crear(GestanteMedicamentoViewModel gestanteMedicamentos)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var result = _gestanteManager.GrabarGestanteMedicamento(gestanteMedicamentos);
                    RegistrarAccion((byte)AccionSesion.Crear, (byte)ObjetoSesion.CrearGestanteMedicamento, result);
                    return result > 0 ? Json(new { Success = 1, GestanteMedicamentoId = result, ex = "" }) : Json(new { Success = 0, ex = new Exception("No se pudo registrar los medicamentos.").Message.ToString() });
                }
            }
            catch (Exception ex)
            {
                // If Sucess== 0 then Unable to perform Save/Update Operation and send Exception to View as JSON 
                return Json(new { Success = 0, ex = ex.Message.ToString() });
            }

            return Json(new { Success = 0, ex = new Exception("No se pudo registrar los medicamentos.").Message.ToString() });
        } 

        public ActionResult GetGestanteData(string dni)
        {
            return RedirectToAction(actionName: "GetGestanteData",
                controllerName: "Gestante",
                routeValues: new { numDni = dni });
        }

        public ActionResult GetMedicamentosPorNombre(string medicamento)
        {
            var medicamentos =  _gestanteManager.GetMedicamentosPorNombre(medicamento);
            return Json(medicamentos, JsonRequestBehavior.AllowGet);
        }

        public ActionResult BuscarGestanteMedicamentos(string numDni, string aPaterno, string aMaterno, string establecimiento, string fechaIni, string fechaFin)
        {
            var page = Convert.ToInt32(Request.Params["page"]);
            var records = Convert.ToInt32(Request.Params["rows"]);
            var sortColumn = Request.Params["sidx"] ?? "";
            var sortDirection = Request.Params["sord"] ?? "asc";

            RegistrarAccion((byte)AccionSesion.Buscar, (byte)ObjetoSesion.ListaGestanteMedicamento, null);
            var listaGestanteMedicamentos = _gestanteManager.ListarGestanteMedicamentos(numDni, aPaterno, aMaterno, establecimiento, fechaIni, fechaFin,
                sortColumn, sortDirection, EstablecimientoRestriccion());
            var count = listaGestanteMedicamentos.Count;

            var jsonDataObject = new
            {
                page = page,
                total = (int)Math.Ceiling((double)count / records),
                records = count,
                rows = listaGestanteMedicamentos.Skip((page - 1) * records).Take(records)
            };
            return new JsonResult()
            {
                Data = jsonDataObject,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                MaxJsonLength = Int32.MaxValue
            };
        }

        public ActionResult BuscarGestanteMedDetalle(int idGMed)
        {
            var listaGestanteMedDetalle = _gestanteManager.ListarGestanteMedDetalle(idGMed);
            var count = listaGestanteMedDetalle.Count;

            var jsonDataObject = new
            {
                page = 1,
                total = count,
                records = count,
                rows = listaGestanteMedDetalle.Take(count)
            };
            return new JsonResult()
            {
                Data = jsonDataObject,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                MaxJsonLength = Int32.MaxValue
            };
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegistrarAccion((byte)AccionSesion.Accesar, (byte)ObjetoSesion.EditarGestanteMedicamento, null);
            var gestanteMedicamento = _gestanteManager.MostrarGestanteMedicamento((int)id);

            if (gestanteMedicamento == null)
            {
                return HttpNotFound();
            }
            ConfigurarMenues();
            ViewBag.EstablecimientoId = new SelectList(_establecimientoManager.ListarEstablecimientos(), "EstablecimientoId", "Descripcion", gestanteMedicamento.EstablecimientoId);
            return View(gestanteMedicamento);
        }

        [HttpPost]
        public JsonResult Edit(GestanteMedicamentoViewModel gestanteMedicamentos)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var result = _gestanteManager.GrabarGestanteMedicamento(gestanteMedicamentos);
                    RegistrarAccion((byte)AccionSesion.Actualizar, (byte)ObjetoSesion.EditarGestanteMedicamento, result);
                    return result > 0 ? Json(new { Success = 1, GestanteMedicamentoId = result, ex = "" }) : Json(new { Success = 0, ex = new Exception("No se pudo registrar los medicamentos.").Message.ToString() });
                }
            }
            catch (Exception ex)
            {
                // If Sucess== 0 then Unable to perform Save/Update Operation and send Exception to View as JSON 
                return Json(new { Success = 0, ex = ex.Message.ToString() });
            }

            return Json(new { Success = 0, ex = new Exception("No se pudo registrar los medicamentos.").Message.ToString() });
        }

        // POST: /GestanteMedicamento/Eliminar
        [HttpPost]
        public JsonResult Eliminar(List<int> ids)
        {
            try
            {
                _gestanteManager.EliminarGestantesMedicamento(ids);
                ids.ForEach(i => RegistrarAccion((byte)AccionSesion.Eliminar, (byte)ObjetoSesion.ListaGestanteMedicamento, i));
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
            return Json(true);
        }

	}
}

Telemonitoreo/Telemonitoreo/Views/GestanteMedicamento/Crear.cshtml
@model Telemonitoreo.Models.GestanteMedicamentoViewModel
@using Telemonitoreo.Utils;

@{
    ViewBag.Title = "Crear";
}

<h2>Asignación de Medicamentos a Gestante</h2>
@Styles.Render("~/Content/DataTables-1.8.1/extras/TableTools/media/css/css")

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary("", new { @class = "text-danger" })
        <div class="form-group">
            <label class="col-md-2 control-label">Número de DNI:</label>
            <div class="col-md-10">
                <div class="input-group">
                    <input id="GestanteDni" name="GestanteDni" type="text" class="form-control" maxlength="8">
                    <input type="hidden" id="KeyGestante" name="KeyGestante">
                    <span class="input-group-btn" style="width: 23% !important;">
                        <button class="btn btn-primary" type="button" onclick="BuscarGestante();">Consultar</button>
                    </span>
                </div>
                @Html.ValidationMessageFor(model => model.GestanteKey, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">Nombres</label>
            <div class="col-md-10">
                <input id="NombresGestante" name="NombresGestante" type="text" class="form-control" readonly="readonly">
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">Apellido Paterno</label>
            <div class="col-md-10">
                <input id="APaternoGestante" name="APaternoGestante" type="text" class="form-control" readonly="readonly">
            </div>
        </div>
        <div class="form-group">
            <label class="col-md-2 control-label">Apellido Materno</label>
            <div class="col-md-10">
                <input id="AMaternoGestante" name="AMaternoGestante" type="text" class="form-control" readonly="readonly">
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NombreMedico, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreMedico, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EstablecimientoId, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownList("EstablecimientoId", null, GlobalConstants.SeleccioneEstablecimiento,
                    htmlAttributes: new {@class = "form-control"})
            </div>
        </div>
        <fieldset style="border: 1px solid #C0C0C0; padding: 10px; width: 70%;">
            <legend style="font-weight: bold; margin: 0px; border: 0px; width: auto; font-size: 18px;">Medicamentos</legend>
            <div class="form-group">
                <label class="col-md-2 control-label">Medicamento</label>
                <div class="col-md-10">
                    <input id="Descripcion" name="Descripcion" type="text" class="form-control">
                    <input type="hidden" id="MedicamentoId" name="MedicamentoId">
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Dosis</label>
                <div class="col-md-10">
                    <input id="Dosis" name="Dosis" type="text" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Frecuencia diaria</label>
                <div class="col-md-10">
                    <input id="Cantidad" name="Cantidad" type="text" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Núm. de días</label>
                <div class="col-md-10">
                    <input id="Dias" name="Dias" type="text" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Indicaciones</label>
                <div class="col-md-10">
                    <div class="input-group">
                        <textarea id="Instrucciones" name="Instrucciones" class="form-control" style="-moz-resize: none;-ms-resize: none;-o-resize: none;resize: none;"></textarea>
                        <span class="input-group-btn" style="width: 10% !important;">
                            <button type="button" class="btn btn-primary" onclick="AddMedicina();">+</button>
                        </span>
                    </div>
                </div>
            </div>
            <table class="tbl hijos" style="width:750px;" id="tbl">
                <thead>
                    <tr>
                        <th style="width: 70px;">ID</th>
                        <th style="width: 200px;">Medicamento</th>
                        <th style="width: 90px;">Dosis</th>
                        <th style="width: 90px;">Nº de días</th>
                        <th style="width: 80px;">Frecuencia</th>
                        <th style="width: 220px;">Indicaciones</th>
                    </tr>
                </thead>

                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model.Medicamentos)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayTextFor(i => item.MedicamentoId)
                                </td>
                                <td>
                                    @Html.DisplayTextFor(i => item.Descripcion)
                                </td>
                                <td>
                                    @Html.DisplayTextFor(i => item.Dosis)
                                </td>
                                <td>
                                    @Html.DisplayTextFor(i => item.Dias)
                                </td>
                                <td>
                                    @Html.DisplayTextFor(i => item.Cantidad)
                                </td>
                                <td>
                                    @Html.DisplayTextFor(i => item.Instrucciones)
                                </td>
                            </tr>
                        }
                    }

                </tbody>
            </table>
            <input type="button" value="Borrar Medicamento" onclick=" DeleteMedicina() " />
        </fieldset>
        <br/>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Grabar" class="btn btn-primary" onclick="GuardarMed()" />
            </div>
        </div>
    </div>
    <div id="ajaxpartialtarget"></div>
}
<div>
    @Html.ActionLink("Ver Listado de Medicamentos", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqDatePicker")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/DataTables")
    @Scripts.Render("~/bundles/jqGestanteMedicamentosForm")
}

Telemonitoreo/Telemonitoreo/Views/GestanteMedicamento/Edit.cshtml
@model Telemonitoreo.Models.GestanteMedicamentoViewModel
@using Telemonitoreo.Utils;

@{
    ViewBag.Title = "Edit";
}

<h2>Editar Asignación de Medicamentos a Gestante</h2>
@Styles.Render("~/Content/DataTables-1.8.1/extras/TableTools/media/css/css")
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary("", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.GestanteMedicamentoId, new { htmlAttributes = new { @class = "form-control" } })
        <div class="form-group">
            @Html.LabelFor(model => model.GestanteDni, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GestanteDni, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                <input type="hidden" id="KeyGestante" name="KeyGestante" value="@Model.GestanteKey">
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.APaterno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.APaterno, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AMaterno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AMaterno, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NombreMedico, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreMedico, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.EstablecimientoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EstablecimientoId", null, GlobalConstants.SeleccioneEstablecimiento,
                htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
        <fieldset style="border: 1px solid #C0C0C0; padding: 10px; width: 70%;">
            <legend style="font-weight: bold; margin: 0px; border: 0px; width: auto; font-size: 18px;">Medicamentos</legend>
            <div class="form-group">
                <label class="col-md-2 control-label">Medicamento</label>
                <div class="col-md-10">
                    @Html.TextBox("Descripcion", "", htmlAttributes: new { @class = "form-control" })
                    @Html.Hidden("MedicamentoId")
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Dosis</label>
                <div class="col-md-10">
                    @Html.TextBox("Dosis", "", htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Frecuencia diaria</label>
                <div class="col-md-10">
                    @Html.TextBox("Cantidad", "", htmlAttributes: new {@class = "form-control"})
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Núm. de días</label>
                <div class="col-md-10">
                    @Html.TextBox("Dias", "", htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Indicaciones</label>
                <div class="col-md-10">
                    <div class="input-group">
                        @Html.TextArea("Instrucciones", "", htmlAttributes: new { @class = "form-control", @style = "-moz-resize: none;-ms-resize: none;-o-resize: none;resize: none;" })
                        <span class="input-group-btn" style="width: 10% !important;">
                            <button type="button" class="btn btn-primary" onclick="AddMedicinaEdit();">+</button>
                        </span>
                    </div>
                </div>
            </div>
            <table class="tbl hijos" id="tbl">
                <thead>
                    <tr>
                        <th class="col-md-1">ID</th>
                        <th class="col-md-1">ID Medicamento</th>
                        <th class="col-md-2">Medicamento</th>
                        <th class="col-md-2">Dosis</th>
                        <th class="col-md-2">Nº de días</th>
                        <th class="col-md-2">Frecuencia</th>
                        <th class="col-md-3">Indicaciones</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model.Medicamentos)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayTextFor(i => item.GestanteMedicamentoDetalleId)
                                </td>
                                <td>
                                    @Html.DisplayTextFor(i => item.MedicamentoId)
                                </td>
                                <td>
                                    @Html.DisplayTextFor(i => item.Descripcion)
                                </td>
                                <td>
                                    @Html.DisplayTextFor(i => item.Dosis)
                                </td>
                                <td>
                                    @Html.DisplayTextFor(i => item.Dias)
                                </td>
                                <td>
                                    @Html.DisplayTextFor(i => item.Cantidad)
                                </td>
                                <td>
                                    @Html.DisplayTextFor(i => item.Instrucciones)
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <input type="button" value="Borrar Medicamento" onclick=" DeleteMedicina() " />
        </fieldset>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Grabar" class="btn btn-primary" onclick="GuardarMedEdit()" />
            </div>
        </div>
    </div>
    <div id="ajaxpartialtarget"></div>
}
<br/>
<div>
    @Html.ActionLink("Ver Listado de Medicamentos", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqDatePicker")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/DataTables")
    @Scripts.Render("~/bundles/jqGestanteMedicamentosForm")
}

Telemonitoreo/Telemonitoreo/Views/GestanteMedicamento/Index.cshtml
@using Telemonitoreo.Utils;

@{
    ViewBag.Title = "Lista de Medicamentos Asignados";
}

<h2>Lista de Medicamentos Asignados a Gestantes</h2>
@using (Html.BeginForm("ExportExcel", "GestanteMedicamento", FormMethod.Post, new { id = "ListadoGestanteMedicamento", 
    enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-md-4">
            <div class="col-md-3">
                <label for="NroDocumento">DNI</label>
            </div>
            <div class="col-md-9">
                <input name="NroDocumento" class="form-control" id="NroDocumento" type="text" maxlength="8">
            </div>
        </div>
        <div class="col-md-4">
            <div class="col-md-3">
                <label for="APaterno">A. Paterno</label>
            </div>
            <div class="col-md-9">
                <input name="APaterno" class="form-control" id="APaterno" type="text">
            </div>
        </div>
        <div class="col-md-4">
            <div class="col-md-3">
                <label for="AMaterno">A. Materno</label>
            </div>
            <div class="col-md-9">
                <input name="AMaterno" class="form-control" id="AMaterno" type="text">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="col-md-3">
                <label>Est. de Salud</label>
            </div>
            <div class="col-md-9">
                @Html.DropDownList("EstablecimientoId", null, GlobalConstants.SeleccioneEstablecimiento, 
                htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
        <div class="col-md-4">
            <div class="col-md-3">
                <label for="FechaI">Fecha inicio (Asignación)</label>
            </div>
            <div class="col-md-9">
                <input name="FechaI" class="form-control" id="FechaI" type="text">
            </div>
        </div>

        <div class="col-md-4">
            <div class="col-md-3">
                <label for="FechaF">Fecha fin (Asignación)</label>
            </div>
            <div class="col-md-9">
                <input name="FechaF" class="form-control" id="FechaF" type="text">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-8">
            <div class="col-md-9 col-md-offset-3">
                <input name="btnBuscar" class="btn btn-primary btn-group-sm" id="btnBuscar" type="button" value="Buscar">
            </div>
        </div>
    </div>
}
<div class="row">
    <div class="col-md-11">
        <table id="sg1"></table>
        <div id="psg1"></div>
        <div id="pager"></div>
    </div>
</div>
<div class="row">
    <div class="col-md-8 text-left">
        <input name="btnEliminar" class="btn btn-primary" id="btnEliminar" type="button" value="Deshabilitar">
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqGestanteMedicamentos")
}