Telemonitoreo/Telemonitoreo/Controllers/SesionLogController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Telemonitoreo.Business;
using Telemonitoreo.Enums;
using Telemonitoreo.Utils;

namespace Telemonitoreo.Controllers
{
    public class SesionLogController : BaseController
    {
        readonly SesionManager _sesionManager = new SesionManager();
        //
        // GET: /Establecimiento/
        public ActionResult Index()
        {
            ConfigurarMenues();
            RegistrarAccion((byte)AccionSesion.Accesar, (byte)ObjetoSesion.ListaSesiones, null);
            return View();
        }

        public ActionResult FilterIndex()
        {
            ConfigurarMenues();
            RegistrarAccion((byte)AccionSesion.Accesar, (byte)ObjetoSesion.ListaSesionesUsuario, null);
            return View();
        }

        // GET: BuscarGestantes
        public ActionResult BuscarSesiones(string numDni, string aPaterno, string aMaterno, string menu, string fechaIni, string fechaFin)
        {
            var page = Convert.ToInt32(Request.Params["page"]);
            var records = Convert.ToInt32(Request.Params["rows"]);
            var sortColumn = Request.Params["sidx"] ?? "";
            var sortDirection = Request.Params["sord"] ?? "asc";

            RegistrarAccion((byte)AccionSesion.Buscar, (byte)ObjetoSesion.ListaSesiones, null);

            var listaSesiones = _sesionManager.ListarSesiones(numDni, aPaterno, aMaterno, menu, fechaIni, fechaFin,sortColumn, sortDirection);
            var count = listaSesiones.Count;

            var jsonDataObject = new
            {
                page = page,
                total = (int)Math.Ceiling((double)count / records),
                records = count,
                rows = listaSesiones.Skip((page - 1) * records).Take(records)
            };
            return new JsonResult()
            {
                Data = jsonDataObject,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                MaxJsonLength = Int32.MaxValue
            };
        }

        public ActionResult BuscarSesionesUsuario(string menu, string fechaIni, string fechaFin)
        {
            var page = Convert.ToInt32(Request.Params["page"]);
            var records = Convert.ToInt32(Request.Params["rows"]);
            var sortColumn = Request.Params["sidx"] ?? "";
            var sortDirection = Request.Params["sord"] ?? "asc";
            
            var numDni = "ADMIN";
            if (Request.IsAuthenticated)
            {
                numDni = User.Identity.Name;
            }

            RegistrarAccion((byte)AccionSesion.Buscar, (byte)ObjetoSesion.ListaSesionesUsuario, null);

            var listaSesiones = _sesionManager.ListarSesiones(numDni, "", "", menu, fechaIni, fechaFin, sortColumn, sortDirection);
            var count = listaSesiones.Count;

            var jsonDataObject = new
            {
                page = page,
                total = (int)Math.Ceiling((double)count / records),
                records = count,
                rows = listaSesiones.Skip((page - 1) * records).Take(records)
            };
            return new JsonResult()
            {
                Data = jsonDataObject,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                MaxJsonLength = Int32.MaxValue
            };
        }

        public ActionResult ExportarExcel(FormCollection form)
        {
            try
            {
                var numDni = form["NroDni"];
                var aPaterno = form["APaterno"];
                var aMaterno = form["AMaterno"];
                var fechaIni = form["FechaI"];
                var fechaFin = form["FechaF"];
                var menu = form["Menu"];
                
                var sortColumn = form["hdSortColumn"] ?? "UsuarioKey";
                var sortDirection = form["hdSortDirection"] ?? "asc";

                RegistrarAccion((byte)AccionSesion.ExportExcel, (byte)ObjetoSesion.ListaSesiones, null);
                var listaSesiones = _sesionManager.ListarSesiones(numDni, aPaterno, aMaterno, menu, fechaIni, fechaFin,sortColumn, sortDirection);

                var listaSesionesExcel = from o in listaSesiones
                                                 select new
                                                 {
                                                     ID_Sesion = o.RegistroEventoKey,
                                                     DNI = o.Dni,
                                                     Nombres = o.Nombre,
                                                     A_Paterno = o.APaterno,
                                                     A_Materno = o.AMaterno,
                                                     o.Accion,
                                                     Menu_Objeto = o.Menu,
                                                     ID_Registro = o.IdRegistro,
                                                     Fecha = o.EventoFecha,
                                                     IP = o.Origen
                                                 };

                ExcelExport.ExportToSpreadsheet(listaSesionesExcel.CopyToDataTable(), "Sesiones");
                return View();
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e;
                return PartialView("Error");
            }
        }

        public ActionResult ExportarExcelUsuario(FormCollection form)
        {
            try
            {
                var fechaIni = form["FechaI"];
                var fechaFin = form["FechaF"];
                var menu = form["Menu"];
                
                var sortColumn = form["hdSortColumn"] ?? "UsuarioKey";
                var sortDirection = form["hdSortDirection"] ?? "asc";

                var numDni = "ADMIN";
                if (Request.IsAuthenticated)
                {
                    numDni = User.Identity.Name;
                }

                RegistrarAccion((byte)AccionSesion.ExportExcel, (byte)ObjetoSesion.ListaSesionesUsuario, null);
                var listaSesiones = _sesionManager.ListarSesiones(numDni, "", "", menu, fechaIni, fechaFin,sortColumn, sortDirection);

                var listaSesionesExcel = from o in listaSesiones
                                                 select new
                                                 {
                                                     ID_Sesion = o.RegistroEventoKey,
                                                     DNI = o.Dni,
                                                     Nombres = o.Nombre,
                                                     A_Paterno = o.APaterno,
                                                     A_Materno = o.AMaterno,
                                                     o.Accion,
                                                     Menu_Objeto = o.Menu,
                                                     ID_Registro = o.IdRegistro,
                                                     Fecha = o.EventoFecha,
                                                     IP = o.Origen
                                                 };

                ExcelExport.ExportToSpreadsheet(listaSesionesExcel.CopyToDataTable(), "Sesiones de Usuario");
                return View();
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = e;
                return PartialView("Error");
            }
        }
	}
}

Telemonitoreo/Telemonitoreo/Views/SesionLog/FilterIndex.cshtml
@{
    ViewBag.Title = "FilterIndex";
}

<h2>Listado de Sesiones de Usuario Actual</h2>
@using (Html.BeginForm("ExportarExcelUsuario", "SesionLog", FormMethod.Post, new { id = "ListadoSesionesUsuario", enctype = "multipart/form-data" }))
{
   <div class="row">
        <div class="col-md-4">
            <div class="col-md-3">
                <label for="Menu">Opción / Menú</label>
            </div>
            <div class="col-md-9">
                <input name="Menu" class="form-control" id="Menu" type="text">
            </div>
        </div>
        <div class="col-md-4">
            <div class="col-md-3">
                <label for="FechaI">Fecha Inicio</label>
            </div>
            <div class="col-md-9">
                <input name="FechaI" class="text-box single-line datepicker textbox-bring-to-front" id="FechaI" type="text">
            </div>
        </div>

        <div class="col-md-4">
            <div class="col-md-3">
                <label for="FechaF">Fecha Final</label>
            </div>
            <div class="col-md-9">
                <input name="FechaF" class="text-box single-line datepicker textbox-bring-to-front" id="FechaF" type="text">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-8">
            <div class="col-md-9 col-md-offset-3">
                <input name="btnBuscar" class="btn btn-primary btn-group-sm" id="btnBuscar" type="button" value="Buscar">
            </div>
        </div>
    </div>
    <input type="hidden" id="hdSortColumn" name="hdSortColumn">
    <input type="hidden" id="hdSortDirection" name="hdSortDirection">
}
<div class="row">
    <div class="col-md-11">
        <div class="text-left">
            <input name="btnExportarExcel" class="btn btn-primary btn-group-sm" id="btnExportarExcel" type="button" value="Exportar">
        </div>
        <table id="gridView"><tr><td></td></tr></table>
        <div id="pager"></div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqSesionLogUsuario")
    @Scripts.Render("~/bundles/jqDatePicker")
}

Telemonitoreo/Telemonitoreo/Views/SesionLog/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Listado de Sesiones</h2>
@using (Html.BeginForm("ExportarExcel", "SesionLog", FormMethod.Post, new { id = "ListadoSesiones", enctype = "multipart/form-data" }))
{
    <div class="row">
        <div class="col-md-4">
            <div class="col-md-3">
                <label for="NroDni">DNI</label>
            </div>
            <div class="col-md-9">
                <input name="NroDni" class="form-control" id="NroDni" type="text" maxlength="8">
            </div>
        </div>
        <div class="col-md-4">
            <div class="col-md-3">
                <label for="FechaI">Fecha Inicio</label>
            </div>
            <div class="col-md-9">
                <input name="FechaI" class="text-box single-line datepicker textbox-bring-to-front" id="FechaI" type="text">
            </div>
        </div>

        <div class="col-md-4">
            <div class="col-md-3">
                <label for="FechaF">Fecha Final</label>
            </div>
            <div class="col-md-9">
                <input name="FechaF" class="text-box single-line datepicker textbox-bring-to-front" id="FechaF" type="text">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="col-md-3">
                <label for="Menu">Opción / Menú</label>
            </div>
            <div class="col-md-9">
                <input name="Menu" class="form-control" id="Menu" type="text">
            </div>
        </div>
        <div class="col-md-4">
            <div class="col-md-3">
                <label for="APaterno">Apellido Paterno</label>
            </div>
            <div class="col-md-9">
                <input name="APaterno" class="form-control" id="APaterno" type="text">
            </div>
        </div>
        <div class="col-md-4">
            <div class="col-md-3">
                <label for="AMaterno">Apellido Materno</label>
            </div>
            <div class="col-md-9">
                <input name="AMaterno" class="form-control" id="AMaterno" type="text">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-8">
            <div class="col-md-9 col-md-offset-3">
                <input name="btnBuscar" class="btn btn-primary btn-group-sm" id="btnBuscar" type="button" value="Buscar">
            </div>
        </div>
    </div>
    <input type="hidden" id="hdSortColumn" name="hdSortColumn">
    <input type="hidden" id="hdSortDirection" name="hdSortDirection">
}
<div class="row">
    <div class="col-md-11">
        <div class="text-left">
            <input name="btnExportarExcel" class="btn btn-primary btn-group-sm" id="btnExportarExcel" type="button" value="Exportar">
        </div>
        <table id="gridView"><tr><td></td></tr></table>
        <div id="pager"></div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqSesionLog")
    @Scripts.Render("~/bundles/jqDatePicker")
}